views.py
# builtin modules :
import os
from datetime import datetime , timedelta
import datetime as dt

# external modules :
from flask import Blueprint , request ,  render_template , session , abort , make_response , redirect , url_for , json
from werkzeug.security import check_password_hash 
from flask_login import login_user , current_user , login_required , logout_user
import jwt

# third party modules :
from settings import BASE_DIR
from extensions import add_user , add_media
from extensions import *
from settings import SECRET_KEY


Oops = Blueprint('Oops' , __name__)

@Oops.route('/signup' , methods= ['GET','POST'])
@Oops.route('/join' , methods= ['GET','POST'])
def signup() :
    if request.method == 'POST' :

        user_name = request.form.get('user_name')
        card_number = request.form.get('card_number')
        email = request.form.get('email')
        password = request.form.get('password')
        picture = request.files.get('profile_pic')

        if user_name and card_number and email and password :
            picture_path = None
            if picture :
                extension = picture.filename.split('.')[-1]
                if extension in ('png' , 'jpg' , 'jpeg') :
                    picture_path = os.path.join(BASE_DIR , 'static' , 'imgs' , str(datetime.utcnow()).replace(':','-').replace(' ','_') , extension)
                    picture.save(picture_path)
                    add_media(picture_path , os.path.getsize(picture_path))


            add_user(user_name , card_number , email , password , picture_path)

            return 'user added seccufuly !'

    return render_template('signup.html')

@Oops.route('/signin' , methods = ['GET' , 'POST'])
@Oops.route('/login' , methods = ['GET' , 'POST'])
def signin() :
    if request.method == 'POST' :
        card_number = request.form.get('card_number')
        password = request.form.get('password')

        exist = get_user(card_number = card_number)
        if exist :
            if check_password_hash(exist.password_hash , password) :
                login_user(exist)

                user_info = {
                    'id' : current_user.id ,
                    'name' : current_user.user_name ,
                    'email' : current_user.email ,
                }

                token = jwt.api_jwt.encode(user_info , SECRET_KEY)

                response = make_response(redirect('/'))
                response.set_cookie('token',token , timedelta(days = 365) , secure=True)

                return response
            
            return 'wrong password'
        return 'card_number not found'

    return render_template('signin.html')

@Oops.route('/send-reset-password-email' , methods = ['GET','POST'])
def send_reset_password_email() :
    if request.method == 'POST' :
        email = request.form.get('email')
        if email :
            session['email'] = email
            return render_template('send_reset_password_email.html') # here send that the email sent
    return render_template('send_reset_password_email.html')

@Oops.route('/reset_password')
def reset_password() :
    # if session.get('email') :
    #     return render_template('reset_password.html')
    # abort(401) # page not authorized
    return render_template('reset_password.html')

@login_required
@Oops.route('/logout')
def logout() :
    logout_user()
    return redirect(url_for('Oops.signin'))

templates/changePassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Opps!</title>
    <!-- --------- syle css file ------------ -->
    <link rel="stylesheet" href="{{ url_for('static' , filename='css/changePassword.css') }}">
    <link rel="stylesheet" href="{{ url_for('static' , filename='css/common.css') }}">
    <link rel="stylesheet" href="{{ url_for('static' , filename='css/exp.css') }}">
    <!-- <----------- font from google ------------ -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@200;300;400;600;900&family=Ubuntu:wght@300;400;500;700&display=swap" rel="stylesheet">
<!-- ------- java script -------------- -->
<script defer src="{{ url_for ('static' filename='js/exp.js') }}" type="module"></script>
<script defer src="{{ url_for ('static' filename='js/changePassword.js') }}" type="module"></script>
</head>
<body>
    <!-- --------- intro page --------- -->
    <div class="container">
                <!---------- change password ----------->
                <div class="changePassword">
                    <div class="info">
                        <h1><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M144 144v48H304V144c0-44.2-35.8-80-80-80s-80 35.8-80 80zM80 192V144C80 64.5 144.5 0 224 0s144 64.5 144 144v48h16c35.3 0 64 28.7 64 64V448c0 35.3-28.7 64-64 64H64c-35.3 0-64-28.7-64-64V256c0-35.3 28.7-64 64-64H80z"/></svg></h1>
                        <p class="warning">turn you change password it should be strong and scure!!</p>
                        <form action="">
                            <!-- -------- input pswrd --------- -->
                            <span class="password">
                                <svg id="warn" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M256 32c14.2 0 27.3 7.5 34.5 19.8l216 368c7.3 12.4 7.3 27.7 .2 40.1S486.3 480 472 480H40c-14.3 0-27.6-7.7-34.7-20.1s-7-27.8 .2-40.1l216-368C228.7 39.5 241.8 32 256 32zm0 128c-13.3 0-24 10.7-24 24V296c0 13.3 10.7 24 24 24s24-10.7 24-24V184c0-13.3-10.7-24-24-24zm32 224c0-17.7-14.3-32-32-32s-32 14.3-32 32s14.3 32 32 32s32-14.3 32-32z"></path></svg>
                                <secur class="scurity"></secur>
                                <img src="{{ url_for('static' , filename='imgs/imgconfirm/lock-solid.svg') }}" alt="">
                                <input type="password" name="password" placeholder="password">
                            </span>
                            <!-- -------- input pswrd2 --------- -->
                            <span class="Confpassword">
                                <!-- img correct check of password -->
                                <svg id="checkicon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M470.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L192 338.7 425.4 105.4c12.5-12.5 32.8-12.5 45.3 0z"/></svg>
                                <svg id="warn" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M256 32c14.2 0 27.3 7.5 34.5 19.8l216 368c7.3 12.4 7.3 27.7 .2 40.1S486.3 480 472 480H40c-14.3 0-27.6-7.7-34.7-20.1s-7-27.8 .2-40.1l216-368C228.7 39.5 241.8 32 256 32zm0 128c-13.3 0-24 10.7-24 24V296c0 13.3 10.7 24 24 24s24-10.7 24-24V184c0-13.3-10.7-24-24-24zm32 224c0-17.7-14.3-32-32-32s-32 14.3-32 32s14.3 32 32 32s32-14.3 32-32z"></path></svg>
                                <secur class="scurity"></secur>
                                <img src="{{ url_for('static' , filename='imgs/imgconfirm/lock-solid.svg') }} " alt="">
                                <input  type="password" name="password" placeholder="confirm your password">
                            </span>

                            <!-- ----------- button ---------- -->
                            <button id="send">NEXT</button>
                            <!-- <input type="submit" id="send" > -->
                        </form>
                    </div>
                    <div class="haveAccount">Don't have an account? <a href="{{ url_for('Oops.signup') }}" id="signUp">Join Now</a></div>
                </div>
    </div>
</body>
</html>

templates/intro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Opps!</title>
    <!-- --------- syle css file ------------ -->
    <link rel="stylesheet" href="{{ url_for('static' , filename='css/intro.css') }}">
    <!-- <----------- font from google ------------ -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@200;300;400;600;900&family=Ubuntu:wght@300;400;500;700&display=swap" rel="stylesheet">
<!-- ------- java script -------------- -->
<script defer src="{{ url_for('static' , filename='js/intro.js') }}"></script>
</head>
<body>
    <!-- --------- intro page --------- -->
    <div class="container">
    </div>
</body>
<span id="arrow" >
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--! Font Awesome Pro 6.2.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M9.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l160 160c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.2 288 416 288c17.7 0 32-14.3 32-32s-14.3-32-32-32l-306.7 0L214.6 118.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-160 160z"/></svg>
</span>
</html>

templates/main.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>main</title>
    <!-- file css -->
    <link rel="stylesheet" href="{{ url_for('static' , filename='css/main.css') }}">
    <!-- <----------- font from google ------------ -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@200;300;400;600;900&family=Ubuntu:wght@300;400;500;700&display=swap"
        rel="stylesheet">
    <!-- file js -->
    <script defer src="{{ url_for('static' , filename='js/main.js') }}"></script>
</head>

<body>
    <script>
        
        let path = '{{ path }}' ;
            
    </script>
</body>
</html>

templates/reset_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Opps!</title>
    <!-- --------- syle css file ------------ -->
    <link rel="stylesheet" href="{{ url_for('static' , filename='css/common.css') }}">
    <link rel="stylesheet" href="{{ url_for('static' , filename='css/code.css') }}">
    <!-- <----------- font from google ------------ -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@200;300;400;600;900&family=Ubuntu:wght@300;400;500;700&display=swap" rel="stylesheet">
<!-- ------- java script -------------- -->
<script defer src="{{ url_for('static' , filename='js/code.js' ) }}" type="module"></script>
<script defer src="{{ url_for('static' , filename='js/exp.js') }}" type="module"></script>
</head>
<body>
    <!-- --------- intro page --------- -->
    <div class="container">
      <!-- -------- set code that send it ------- -->
      <div class="code">
        <div class="info">
            <img src="{{ url_for('static' , filename='imgs/imgcode/authentication.svg') }}" alt="">
            <p class="warning">we send a code in your email include 6 numbers cheak it and write here</p>
            <form action="">
                <!-- -------- input email --------- -->
                <img class="envlop" src="{{ url_for('static' , filename='imgs/imgsignUp/envelope-solid.svg') }}" alt="">
                    <input type="email" name="email" placeholder="email">
                    <input type="submit" value="SEND">
                    <svg id="warn" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                        <path d="M256 32c14.2 0 27.3 7.5 34.5 19.8l216 368c7.3 12.4 7.3 27.7 .2 40.1S486.3 480 472 480H40c-14.3 0-27.6-7.7-34.7-20.1s-7-27.8 .2-40.1l216-368C228.7 39.5 241.8 32 256 32zm0 128c-13.3 0-24 10.7-24 24V296c0 13.3 10.7 24 24 24s24-10.7 24-24V184c0-13.3-10.7-24-24-24zm32 224c0-17.7-14.3-32-32-32s-32 14.3-32 32s14.3 32 32 32s32-14.3 32-32z"></path>
                    </svg>
                <!-- ----------- button ---------- -->
            </form>
        </div>
        <div class="haveAccount">Don't have an account? <a href="{{ url_for('Oops.signup') }}" id="signUp">Join Now</a></div>
    </div>
    </div>
</body>
</html>

templates/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Opps!</title>
    <!-- --------- syle css file ------------ -->
    <link rel="stylesheet" href="{{ url_for('static' , filename='css/signin.css') }}">
    <link rel="stylesheet" href="{{ url_for('static' , filename='css/common.css') }}">
    <link rel="stylesheet" href="{{ url_for('static' , filename='css/exp.css') }}">
    <!-- <----------- font from google ------------ -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@200;300;400;600;900&family=Ubuntu:wght@300;400;500;700&display=swap" rel="stylesheet">
<!-- ------- java script -------------- -->
<script defer src="{{ url_for('static' , filename='js/signin.js') }}" type="module"></script>
<script defer src="{{ url_for('static' , filename='js/exp.js') }}" type="module"></script>
</head>
<body>
    <!-- --------- intro page --------- -->
    <div class="container">
              <!-- ---- sign in ---------- -->
              <div class="loginSignIn">
                <div class="txt-intro">
                    <h2>Welcome back</h2>
                    <span>Sign In to back ypur account</span>
                </div>
                <div class="info">
                    <div class="imgUser">
                        
                    </div>
                    <h1>Log In</h1>
                    <form action="" method="post">
                        <!-- -------- input number cart --------- -->
                        <span class="numbercart">
                            <svg id="warn" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M256 32c14.2 0 27.3 7.5 34.5 19.8l216 368c7.3 12.4 7.3 27.7 .2 40.1S486.3 480 472 480H40c-14.3 0-27.6-7.7-34.7-20.1s-7-27.8 .2-40.1l216-368C228.7 39.5 241.8 32 256 32zm0 128c-13.3 0-24 10.7-24 24V296c0 13.3 10.7 24 24 24s24-10.7 24-24V184c0-13.3-10.7-24-24-24zm32 224c0-17.7-14.3-32-32-32s-32 14.3-32 32s14.3 32 32 32s32-14.3 32-32z"></path></svg>
                            <img src="{{ url_for('static' , filename='imgs/imgSignin/credit-card-regular.svg') }}" alt="">
                            <input type="number" name="card_number" placeholder="number your cart">
                        </span>
                        <!-- -------- input password --------- -->
                        <span class="password">
                            <svg id="warn" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M256 32c14.2 0 27.3 7.5 34.5 19.8l216 368c7.3 12.4 7.3 27.7 .2 40.1S486.3 480 472 480H40c-14.3 0-27.6-7.7-34.7-20.1s-7-27.8 .2-40.1l216-368C228.7 39.5 241.8 32 256 32zm0 128c-13.3 0-24 10.7-24 24V296c0 13.3 10.7 24 24 24s24-10.7 24-24V184c0-13.3-10.7-24-24-24zm32 224c0-17.7-14.3-32-32-32s-32 14.3-32 32s14.3 32 32 32s32-14.3 32-32z"></path></svg>
                            <secur class="scurity">easy</secur>
                            <img src="{{ url_for('static' , filename='imgs/imgSignin/lock-solid.svg') }}" alt="">
                            <input type="password" name="password" placeholder="password">
                        </span>
                        <a href="{{ url_for('Oops.reset_password') }}" id="forget">Forget Password?</a>
                        <!-- ----------- button ---------- -->
                        <button id="send">LOGIN</button>
                    </form>
                </div>
                <div class="haveAccount">Don't have an account? <a onclick="click()" href="{{ url_for('Oops.signup') }}" id="signUp">Join Now</a></div>
            </div>
    </div>
</body>
</html>

templates/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,user-scalable=no">
    <title>Opps!</title>
    <!-- --------- syle css file ------------ -->
    <link rel="stylesheet" href="{{ url_for('static' , filename='css/signup.css') }}">
    <link rel="stylesheet" href="{{ url_for('static' , filename='css/common.css') }}">
    <link rel="stylesheet" href="{{ url_for('static' , filename='css/takeph.css') }}">
    <link rel="stylesheet" href="{{ url_for('static' , filename='css/exp.css') }}">
    <!-- <----------- font from google ------------ -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@200;300;400;600;900&family=Ubuntu:wght@300;400;500;700&display=swap"
        rel="stylesheet">
    <!-- ------- java script -------------- -->
    <script defer src="{{ url_for('static' , filename='js/signup.js') }}" type="module"></script>
    <script defer src="{{ url_for('static' , filename='js/exp.js') }}" type="module"></script>
</head>

<body>
    <!-- --------- intro page --------- -->
    <div class="container">
        <!-- ---- sign up ---------- -->
        <div class="loginSignUp">
            <div class="txt-intro">
                <h2>Welcome</h2>
                <span>SignUp into your Account</span>
            </div>
            <div class="info">
                <div class="imgUser">
                    <letter></letter>
                    <span class="takePhoto"><svg xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 512 512"><!--! Font Awesome Pro 6.2.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. -->
                            <path
                                d="M149.1 64.8L138.7 96H64C28.7 96 0 124.7 0 160V416c0 35.3 28.7 64 64 64H448c35.3 0 64-28.7 64-64V160c0-35.3-28.7-64-64-64H373.3L362.9 64.8C356.4 45.2 338.1 32 317.4 32H194.6c-20.7 0-39 13.2-45.5 32.8zM256 384c-53 0-96-43-96-96s43-96 96-96s96 43 96 96s-43 96-96 96z" />
                        </svg></span>
                </div>
                <h1>Sign Up</h1>
                <form action="" method="post">
                    <!-- -------- input name --------- -->
                    <span class="username">
                        <svg id="warn" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                            <path
                                d="M256 32c14.2 0 27.3 7.5 34.5 19.8l216 368c7.3 12.4 7.3 27.7 .2 40.1S486.3 480 472 480H40c-14.3 0-27.6-7.7-34.7-20.1s-7-27.8 .2-40.1l216-368C228.7 39.5 241.8 32 256 32zm0 128c-13.3 0-24 10.7-24 24V296c0 13.3 10.7 24 24 24s24-10.7 24-24V184c0-13.3-10.7-24-24-24zm32 224c0-17.7-14.3-32-32-32s-32 14.3-32 32s14.3 32 32 32s32-14.3 32-32z" />
                        </svg>
                        <img src="{{ url_for('static' , filename='imgs/imgsignUp/user-solid.svg') }}" alt="">
                        <input type="text" name="user_name" placeholder="User Name">
                    </span>
                    <!-- -------- input number cart --------- -->
                    <span class="numbercart">
                        <svg id="warn" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                            <path
                                d="M256 32c14.2 0 27.3 7.5 34.5 19.8l216 368c7.3 12.4 7.3 27.7 .2 40.1S486.3 480 472 480H40c-14.3 0-27.6-7.7-34.7-20.1s-7-27.8 .2-40.1l216-368C228.7 39.5 241.8 32 256 32zm0 128c-13.3 0-24 10.7-24 24V296c0 13.3 10.7 24 24 24s24-10.7 24-24V184c0-13.3-10.7-24-24-24zm32 224c0-17.7-14.3-32-32-32s-32 14.3-32 32s14.3 32 32 32s32-14.3 32-32z" />
                        </svg>
                        <img src="{{ url_for('static' , filename='imgs/imgsignUp/credit-card-regular.svg') }}" alt="">
                        <input type="number" name="card_number" value="" placeholder="number your cart">
                    </span>
                    <!-- -------- input password --------- -->
                    <span class="password">
                        <secur class="scurity">easy</secur>
                        <svg id="warn" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                            <path
                                d="M256 32c14.2 0 27.3 7.5 34.5 19.8l216 368c7.3 12.4 7.3 27.7 .2 40.1S486.3 480 472 480H40c-14.3 0-27.6-7.7-34.7-20.1s-7-27.8 .2-40.1l216-368C228.7 39.5 241.8 32 256 32zm0 128c-13.3 0-24 10.7-24 24V296c0 13.3 10.7 24 24 24s24-10.7 24-24V184c0-13.3-10.7-24-24-24zm32 224c0-17.7-14.3-32-32-32s-32 14.3-32 32s14.3 32 32 32s32-14.3 32-32z" />
                        </svg>
                        <img src="{{ url_for('static' , filename='imgs/imgsignUp/lock-solid.svg') }}" alt="">
                        <input type="password" name="password" placeholder="password">
                    </span>
                    <!-- confirm password -->
                    <!-- -------- input password --------- -->
                    <span class="Confpassword">
                        <secur class="scurity">easy</secur>
                        <svg id="checkicon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                            <path
                                d="M470.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L192 338.7 425.4 105.4c12.5-12.5 32.8-12.5 45.3 0z" />
                        </svg>
                        <svg id="warn" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                            <path
                                d="M256 32c14.2 0 27.3 7.5 34.5 19.8l216 368c7.3 12.4 7.3 27.7 .2 40.1S486.3 480 472 480H40c-14.3 0-27.6-7.7-34.7-20.1s-7-27.8 .2-40.1l216-368C228.7 39.5 241.8 32 256 32zm0 128c-13.3 0-24 10.7-24 24V296c0 13.3 10.7 24 24 24s24-10.7 24-24V184c0-13.3-10.7-24-24-24zm32 224c0-17.7-14.3-32-32-32s-32 14.3-32 32s14.3 32 32 32s32-14.3 32-32z" />
                        </svg>
                        <img src="{{ url_for('static' , filename='imgs/imgsignUp/lock-solid.svg') }}" alt="">
                        <input type="password" name="passWord" placeholder="confirm password">                    </span>
                    <!-- -------- input email --------- -->
                    <span class="email">
                        <svg id="warn" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                            <path
                                d="M256 32c14.2 0 27.3 7.5 34.5 19.8l216 368c7.3 12.4 7.3 27.7 .2 40.1S486.3 480 472 480H40c-14.3 0-27.6-7.7-34.7-20.1s-7-27.8 .2-40.1l216-368C228.7 39.5 241.8 32 256 32zm0 128c-13.3 0-24 10.7-24 24V296c0 13.3 10.7 24 24 24s24-10.7 24-24V184c0-13.3-10.7-24-24-24zm32 224c0-17.7-14.3-32-32-32s-32 14.3-32 32s14.3 32 32 32s32-14.3 32-32z" />
                        </svg>
                        <img src="{{ url_for('static' , filename='imgs/imgsignUp/envelope-solid.svg') }}" alt="">
                        <input type="email" name="email" placeholder="email">
                    </span>
                    <!-- ----------- button ---------- -->
                    <button id="send" name="sendInfo">SIGN UP</button>
                </form>
            </div>
            <div class="haveAccount">Already have an account: <a href="{{ url_for('Oops.signin') }}" id="login">Log In</a>
            </div>
        </div>
    </div>
</body>

</html>